# Generated by Django 5.1.2 on 2025-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='modulos/archivos/'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo_archivo',
            field=models.CharField(blank=True, choices=[('foto', 'Foto'), ('video', 'Video'), ('documento', 'Documento')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
    ]
