# Generated by Django 5.1.2 on 2025-03-31 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0002_modulo_archivo_modulo_tipo_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
