# Generated by Django 5.1.2 on 2025-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0003_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
