# Generated by Django 5.1.2 on 2025-04-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0004_alter_curso_titulo_alter_modulo_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
