# Generated by Django 5.1.2 on 2025-04-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0005_rename_contraseña_usuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='defaults/avatar.webp', null=True, upload_to='usuarios/fotos/'),
        ),
        migrations.CreateModel(
            name='Itinerario_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aulora_bakend.curso')),
                ('itinerario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aulora_bakend.itinerario')),
            ],
        ),
        migrations.AddField(
            model_name='itinerario',
            name='cursos',
            field=models.ManyToManyField(related_name='itinerario', through='Aulora_bakend.Itinerario_curso', to='Aulora_bakend.curso'),
        ),
    ]
