# Generated by Django 5.1.8 on 2025-04-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0006_alter_usuario_foto_perfil'),
        ('Aulora_bakend', '0006_itinerario_alter_usuario_foto_perfil_and_more'),
    ]

    operations = [
    ]
