# Generated by Django 5.1.8 on 2025-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0007_merge_20250410_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
    ]
