# Generated by Django 5.1.8 on 2025-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0008_itinerario_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='materia',
            field=models.CharField(default='Sin materia', max_length=50),
        ),
    ]
