# Generated by Django 5.1.9 on 2025-05-12 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0011_curso_foto_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='itinerarios_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModuloCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aulora_bakend.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
