# Generated by Django 5.1.9 on 2025-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0012_curso_foto_itinerario_inscritos_modulocompletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
