# Generated by Django 5.1.9 on 2025-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0013_curso_foto_itinerario_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
