# Generated by Django 5.1.2 on 2025-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0015_curso_foto_usuario_cursos_completados'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/dcursos.png', null=True, upload_to='cursos/'),
        ),
    ]
