# Generated by Django 5.1.2 on 2025-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0016_curso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/dcursos.png', help_text='.', null=True, upload_to='cursos/'),
        ),
    ]
