# Generated by Django 5.1.9 on 2025-05-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0017_alter_curso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/dcursos.png', null=True, upload_to='cursos/'),
        ),
    ]
