# Generated by Django 5.1.9 on 2025-05-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aulora_bakend', '0018_alter_curso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario_curso',
            name='fecha_agregado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
